-- Données initiales (issues du fichier GESTcpchr) — à exécuter après schema.sql

insert into categories (label) values
  ('1-1- Cotisations Membres (N-1)'),
  ('1-2- Cotisations Membres (N)'),
  ('8-5-Frais Bancaires (N)'),
  ('7-2- Achats Banquet d''Ordre'),
  ('7-1- Achat Agapes et Bar'),
  ('8-2-Achat Décors et Petit Matériel'),
  ('5-2-Capitations GODF (N)'),
  ('3-1-Encaissement AGAPES & BAR'),
  ('8-9-Frais Congrès - Convent GODF'),
  ('9-2.-Cotisation Cercle Emile Payet (N)'),
  ('0-1-TRANSFERT  Caisse > Cpte Courant'),
  ('0-2-TRANSFERT  Caisse > Cpte Hosp.'),
  ('0-3-TRANSFERT Cpte Courant>Cpte Hosp.'),
  ('0-4-TRANSFERT Cpte Hosp>Cpte Courant'),
  ('0-5-ANNULATION DE CREANCE'),
  ('0-6-ANNULATION DE DETTE'),
  ('1-3- Cotisations Membres (N+1)'),
  ('2-1-Tronc de la Veuve'),
  ('2-2-Dons & Médailles Reçus'),
  ('2-3-Subvention GODF'),
  ('2-4-Subvention Externe'),
  ('2-5-Prêts Bancaire / Intérêts Placments'),
  ('2-6-Prêts d''Honneur Reçu (GODF)'),
  ('2-7-Rembourst Prêt d''Honneur Attribué'),
  ('2-8-Rembourst Prêt Trésorier Attribué'),
  ('2-9-Intérêts des placements'),
  ('3-2-Encaissement BANQUET d''ORDRE'),
  ('4-1-Initiation - Élévations (N-1)'),
  ('4-2-Initiation - Élévations (N)'),
  ('4-3- Vente Décors'),
  ('4-4-Produits Divers & Intérêts bancaires'),
  ('5-1-Capitations GODF (N-1)'),
  ('5-3-Taxes & Redevances GODF(N-1)'),
  ('5-4-Taxes & Redevances GODF(N)'),
  ('6-1-Attribution Prêt d''Honneur'),
  ('6-2-Rembourst Prêt d''Honneur (GODF)'),
  ('6-3-Remboursement Prêt Bancaire'),
  ('6-4-Attribution de Médaille'),
  ('6-5-DON Hospitalier'),
  ('6-6-DON Trésorier'),
  ('6-7-Prêt Trésorier de la Loge'),
  ('6-8-Cotisation d''Associations'),
  ('6-9-Rembsmt.Trop Perçu Cotis. Membres'),
  ('8-1-Bibliothèque & Documentation'),
  ('8-3-Papetterie-Secrétariat-Entretien'),
  ('8-4-Frais Bancaires (N-1)'),
  ('8-6-Remboursement Prêts (N-1)'),
  ('8-7-Remboursement Prêts (N)'),
  ('8-8-Frais Missions & Représentation'),
  ('9-1. Cotisation Cercle Emile Payet (N-1)'),
  ('9-3.-Cotisation Cercle Emile Payet (N+1)'),
  ('9-4-Assurances Associatives (N-1)'),
  ('9-5-Assurances Associatives (N)'),
  ('9-6-Assurances Associatives (N+1)'),
  ('9-7-Impôts & Taxes'),
  ('9-8-Charges Diverses')
on conflict (label) do nothing;

insert into forfaits (nom, montant) values
  ('Forfait Apprenti', 0),
  ('Forfait Compagnon', 0),
  ('Forfait Maître', 0);

insert into membres (id, nom, statut, report_n1, cotisation_override) values
  ('ALFONSI André', 'ALFONSI André', 'Permanent', 0, NULL),
  ('ASSABY Willy', 'ASSABY Willy', 'Permanent', -590, NULL),
  ('ASSOUNE Maximin', 'ASSOUNE Maximin', 'Permanent', 0, NULL),
  ('BARAU Jean-Pierre', 'BARAU Jean-Pierre', 'Permanent', 0, NULL),
  ('BLANC Patrick', 'BLANC Patrick', 'Permanent', 0, NULL),
  ('BOUL Jean-Philippe', 'BOUL Jean-Philippe', 'Permanent', 0, NULL),
  ('BOYER Thomas', 'BOYER Thomas', 'Permanent', 0, NULL),
  ('CHIN YIN LIM Christian', 'CHIN YIN LIM Christian', 'Permanent', 0, NULL),
  ('DALLEAU Jacques', 'DALLEAU Jacques', 'Permanent', 0, NULL),
  ('DE Boisvilliers Cédric', 'DE Boisvilliers Cédric', 'Permanent', 0, NULL),
  ('DE LACLOS Jean Claude', 'DE LACLOS Jean Claude', 'Permanent', 0, NULL),
  ('FREYERMUTH Régis', 'FREYERMUTH Régis', 'Affilié', -19.5, NULL),
  ('GOKALSING Edouard', 'GOKALSING Edouard', 'Permanent', -400, NULL),
  ('ICHOUZA Daniel Georges', 'ICHOUZA Daniel Georges', 'Permanent', -20, NULL),
  ('LECHOT Sébastien', 'LECHOT Sébastien', 'Permanent', 0, NULL),
  ('MAGNAN DE BELLEVUE Serge', 'MAGNAN DE BELLEVUE Serge', 'Permanent', -1160, NULL),
  ('MARTIN Anthony', 'MARTIN Anthony', 'Permanent', 391, NULL),
  ('MARTINAZZO Jacques', 'MARTINAZZO Jacques', 'Permanent', 0, NULL),
  ('MEDARD Pierre Jean', 'MEDARD Pierre Jean', 'Permanent', -400, NULL),
  ('MONDON Jean Raymond', 'MONDON Jean Raymond', 'Permanent', 0, NULL),
  ('NAZROO Thierno', 'NAZROO Thierno', 'Permanent', 0, NULL),
  ('PAUBERT Pierre', 'PAUBERT Pierre', 'Permanent', -200, NULL),
  ('PAUL Emmanuel', 'PAUL Emmanuel', 'Permanent', 0, NULL),
  ('PEGOU Jean-Louis', 'PEGOU Jean-Louis', 'Permanent', 0, NULL),
  ('PERIAMODELY Serge', 'PERIAMODELY Serge', 'Permanent', 0, NULL),
  ('PERSEE Alain', 'PERSEE Alain', 'Permanent', 0, NULL),
  ('PORCEL Laurent', 'PORCEL Laurent', 'Permanent', 8.040000000000077, NULL),
  ('RANGAMA Philippe', 'RANGAMA Philippe', 'Permanent', -400, NULL),
  ('ROUECHE Quentin', 'ROUECHE Quentin', 'Permanent', 0, NULL),
  ('TOINETTE Alexandre', 'TOINETTE Alexandre', 'Permanent', 120, NULL),
  ('VANTOMME Philippe', 'VANTOMME Philippe', 'Permanent', 30.870000000000005, NULL),
  ('VAR Ruddy', 'VAR Ruddy', 'Permanent', -200, NULL)
on conflict (id) do nothing;

insert into operations (date, libelle, categorie, montant, compte, membre_id, pointee) values
  ('2026-01-09', 'VAR Ruddy', '1-1- Cotisations Membres (N-1)', 310, 'C.Courant', 'VAR Ruddy', true),
  ('2026-01-20', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-01-09', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-01-09', 'BARAU Jean-Pierre', '7-2- Achats Banquet d''Ordre', -1201.03, 'C.Courant', 'BARAU Jean-Pierre', true),
  ('2026-01-27', 'CHIN YIN LIM Christian', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'CHIN YIN LIM Christian', true),
  ('2026-01-27', 'TOINETTE Alexandre', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'TOINETTE Alexandre', true),
  ('2026-01-27', 'ALFONSI André', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'ALFONSI André', true),
  ('2026-01-27', 'VAR Ruddy', '1-1- Cotisations Membres (N-1)', 100, 'C.Courant', 'VAR Ruddy', true),
  ('2026-01-27', 'Adhérents', '1-1- Cotisations Membres (N-1)', 168.5, 'C.Courant', NULL, true),
  ('2026-01-28', 'ROUECHE Quentin', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'ROUECHE Quentin', true),
  ('2026-01-28', 'ICHOUZA Daniel Georges', '1-2- Cotisations Membres (N)', 250, 'C.Courant', 'ICHOUZA Daniel Georges', true),
  ('2026-01-29', 'PORCEL Laurent', '1-2- Cotisations Membres (N)', 34, 'C.Courant', 'PORCEL Laurent', true),
  ('2026-02-02', 'DALLEAU Jacques', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'DALLEAU Jacques', true),
  ('2026-02-04', 'PERIAMODELY Serge', '1-2- Cotisations Membres (N)', 200, 'C.Courant', 'PERIAMODELY Serge', true),
  ('2026-02-05', 'LECHOT Sébastien', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'LECHOT Sébastien', true),
  ('2026-02-09', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-02-10', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-02-13', 'MARTINAZZO Jacques', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'MARTINAZZO Jacques', true),
  ('2026-02-17', 'PEGOU Jean-Louis', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'PEGOU Jean-Louis', true),
  ('2026-02-17', 'BARAU Jean-Pierre', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'BARAU Jean-Pierre', true),
  ('2026-02-17', 'PAUBERT Pierre', '1-1- Cotisations Membres (N-1)', 300, 'C.Courant', 'PAUBERT Pierre', true),
  ('2026-02-17', 'PAUBERT Pierre', '1-2- Cotisations Membres (N)', 100, 'C.Courant', 'PAUBERT Pierre', true),
  ('2026-02-20', 'BOYER Thomas', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'BOYER Thomas', true),
  ('2026-02-23', 'TOINETTE Alexandre', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'TOINETTE Alexandre', true),
  ('2026-02-27', 'Fournisseurs Divers', '7-1- Achat Agapes et Bar', -172.5, 'C.Courant', NULL, true),
  ('2026-02-27', 'Fournisseurs Divers', '7-1- Achat Agapes et Bar', -15.3, 'C.Courant', NULL, true),
  ('2026-02-27', 'NAZROO Thierno', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'NAZROO Thierno', true),
  ('2026-02-28', 'PORCEL Laurent', '1-2- Cotisations Membres (N)', 34, 'C.Courant', 'PORCEL Laurent', true),
  ('2026-03-01', 'Fournisseurs Divers', '8-2-Achat Décors et Petit Matériel', -42, 'C.Courant', NULL, true),
  ('2026-03-02', 'Fournisseurs Divers', '8-2-Achat Décors et Petit Matériel', -30, 'C.Courant', NULL, true),
  ('2026-03-02', 'BLANC Patrick', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'BLANC Patrick', true),
  ('2026-03-05', 'LECHOT Sébastien', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'LECHOT Sébastien', true),
  ('2026-03-07', 'MEDARD Pierre Jean', '1-1- Cotisations Membres (N-1)', 400, 'C.Courant', 'MEDARD Pierre Jean', true),
  ('2026-03-07', 'VAR Ruddy', '1-1- Cotisations Membres (N-1)', 100, 'C.Courant', 'VAR Ruddy', true),
  ('2026-03-09', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-03-10', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-03-15', 'ASSOUNE Maximin', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'ASSOUNE Maximin', true),
  ('2026-03-15', 'BOUL Jean-Philippe', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'BOUL Jean-Philippe', true),
  ('2026-03-16', 'VANTOMME Philippe', '1-2- Cotisations Membres (N)', 100, 'C.Courant', 'VANTOMME Philippe', true),
  ('2026-03-16', 'PAUL Emmanuel', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'PAUL Emmanuel', true),
  ('2026-03-23', 'TOINETTE Alexandre', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'TOINETTE Alexandre', true),
  ('2026-03-30', 'PORCEL Laurent', '1-2- Cotisations Membres (N)', 34, 'C.Courant', 'PORCEL Laurent', true),
  ('2026-04-07', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-04-08', 'LECHOT Sébastien', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'LECHOT Sébastien', true),
  ('2026-04-10', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-04-16', 'VANTOMME Philippe', '1-2- Cotisations Membres (N)', 33.33, 'C.Courant', 'VANTOMME Philippe', true),
  ('2026-04-20', 'CHIN YIN LIM Christian', '7-1- Achat Agapes et Bar', -863.44, 'C.Courant', 'CHIN YIN LIM Christian', true),
  ('2026-04-21', 'TOINETTE Alexandre', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'TOINETTE Alexandre', true),
  ('2026-04-29', 'GODF', '5-2-Capitations GODF (N)', -1359.69, 'C.Courant', NULL, true),
  ('2026-04-29', 'Région 3', '5-2-Capitations GODF (N)', -293, 'C.Courant', NULL, true),
  ('2026-04-29', 'PORCEL Laurent', '1-2- Cotisations Membres (N)', 34, 'C.Courant', 'PORCEL Laurent', true),
  ('2026-05-06', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-05-07', 'LECHOT Sébastien', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'LECHOT Sébastien', true),
  ('2026-05-10', 'Fournisseurs Divers', '3-1-Encaissement AGAPES & BAR', -120, 'C.Courant', NULL, true),
  ('2026-05-11', 'Fournisseurs Divers', '8-9-Frais Congrès - Convent GODF', -196, 'C.Courant', NULL, true),
  ('2026-05-12', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-05-12', 'GODF', '5-2-Capitations GODF (N)', -1891, 'C.Courant', NULL, true),
  ('2026-05-18', 'VANTOMME Philippe', '1-2- Cotisations Membres (N)', 33.33, 'C.Courant', 'VANTOMME Philippe', true),
  ('2026-05-21', 'TOINETTE Alexandre', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'TOINETTE Alexandre', true),
  ('2026-05-29', 'PORCEL Laurent', '1-2- Cotisations Membres (N)', 34, 'C.Courant', 'PORCEL Laurent', true),
  ('2026-06-02', 'ALFONSI André', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'ALFONSI André', true),
  ('2026-06-02', 'VAR Ruddy', '1-2- Cotisations Membres (N)', 100, 'C.Courant', 'VAR Ruddy', true),
  ('2026-06-02', 'MEDARD Pierre Jean', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'MEDARD Pierre Jean', true),
  ('2026-06-02', 'PERIAMODELY Serge', '1-2- Cotisations Membres (N)', 200, 'C.Courant', 'PERIAMODELY Serge', true),
  ('2026-06-05', 'LECHOT Sébastien', '1-2- Cotisations Membres (N)', 40, 'C.Courant', 'LECHOT Sébastien', true),
  ('2026-06-08', 'Fournisseurs Divers', '8-9-Frais Congrès - Convent GODF', -244.2, 'C.Courant', NULL, true),
  ('2026-06-10', 'Banque C.E.P.A.C.', '8-5-Frais Bancaires (N)', -13.29, 'C.Courant', NULL, true),
  ('2026-06-10', 'DE LACLOS Jean Claude', '1-2- Cotisations Membres (N)', 33.34, 'C.Courant', 'DE LACLOS Jean Claude', true),
  ('2026-06-12', 'FREYERMUTH Régis', '1-2- Cotisations Membres (N)', 300, 'C.Courant', 'FREYERMUTH Régis', true),
  ('2026-06-14', 'DE Boisvilliers Cédric', '1-2- Cotisations Membres (N)', 400, 'C.Courant', 'DE Boisvilliers Cédric', true),
  ('2026-06-15', 'MONDON Jean Raymond', '1-2- Cotisations Membres (N)', 100, 'C.Courant', 'MONDON Jean Raymond', true),
  ('2026-06-12', 'ASSABY Willy', '1-2- Cotisations Membres (N)', 250, 'C.Courant', 'ASSABY Willy', true),
  ('2026-06-15', 'Délégué Congrès Naional', '8-9-Frais Congrès - Convent GODF', -323.4, 'C.Courant', NULL, true),
  ('2026-06-15', 'GODF', '5-2-Capitations GODF (N)', -1592, 'C.Courant', NULL, true),
  ('2026-06-15', 'Cercle Emile Payet', '9-2.-Cotisation Cercle Emile Payet (N)', -2000, 'C.Courant', NULL, true),
  ('2026-06-15', 'RANGAMA Philippe', '1-2- Cotisations Membres (N)', 380, 'C.Courant', 'RANGAMA Philippe', true),
  (NULL, 'CLIENTS & FOURNISSEURS:', '', 171.9, 'C.Courant', NULL, true),
  (NULL, 'Adhérents', '', 921.52, 'C.Courant', NULL, true),
  (NULL, 'Amicale des Mascareignes', '', 2946.25, 'C.Courant', NULL, true),
  (NULL, 'Association V° Ordre', '', 2262.05, 'C.Courant', NULL, true),
  (NULL, 'Assureur Assoc.-MAAF', '', -2348.75, 'C.Courant', NULL, true),
  (NULL, 'Banque C.E.P.A.C.', '', -2039.62, 'C.Courant', NULL, true),
  (NULL, 'Bénéficiaire d''une aide', '', -1569.55, 'C.Courant', NULL, true);

insert into releves (compte, date_debut, date_fin, solde_debut, solde_fin) values
  ('C.Courant', '2026-01-01', NULL, 1653.53, NULL),
  ('C.Hospit', '2026-01-01', NULL, 1580.94, NULL),
  ('Epargne', '2026-01-01', NULL, 3850.67, NULL);
